import { test, expect } from "@playwright/test";

//👩‍💻 📟🔐Authenticate via API  using the storage state generated by the fixture
//When to use:
//Your web application supports authenticating via API that is easier/faster 
// than interacting with the app UI.

/**
 * ┌────────────────────────────────────────────────────────────┐
 * │         Test Block: Uses storageState from saved file       │
 * └────────────────────────────────────────────────────────────┘
 *                   │
 *                   ▼
 *    Playwright auto-loads `apilogin.json` into browser context
 *                   │
 *                   ▼
 *    No need to perform UI login again — already authenticated
 *                   │
 *                   ▼
 *   Test navigates directly to `/myorders` and validates content
 *
 *  Fast, clean, and ideal for stable backend-auth flows!
 */



test.use({ storageState: "playwright/.auth/apilogin.json" });
test("customer sees myaccount page", async ({ page }) => {
  await page.goto("https://practicesoftwaretesting.com/account");
  await expect(page).toHaveURL(/account$/);
  await expect(page.getByRole("columnheader", { name: "Order ID" })).toBeVisible();

});
 