import { test, expect } from "@playwright/test";

//👩‍💼👩‍💻 Authenticate via API  using the storage state generated by the fixture

test.use({ storageState: "playwright/.auth/admin.json" });
test("Admin sees orders page", async ({ page }) => {
  await page.goto("https://bookcart.azurewebsites.net/myorders");
  await expect(page).toHaveURL(/myorders$/);
  await expect(page.getByRole("columnheader", { name: "Order ID" })).toBeVisible();

});
