import { test, expect } from "@playwright/test";

//👩‍💻 📟🔐Authenticate via API  using the storage state generated by the fixture
//When to use:
//Your web application supports authenticating via API that is easier/faster 
// than interacting with the app UI.


test.use({ storageState: "playwright/.auth/apilogin.json" });
test("Admin sees orders page", async ({ page }) => {
  await page.goto("https://bookcart.azurewebsites.net/myorders");
  await expect(page).toHaveURL(/myorders$/);
  await expect(page.getByRole("columnheader", { name: "Order ID" })).toBeVisible();

});
 